language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
python:
  - "2.7"
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION="4.3"
    - python: "3.7"
      env: PLONE_VERSION="5.2"
  fast_finish: true
before-install:
  - sed -ie "s#4.3-latest#$PLONE_VERSION-latest#" buildout.cfg
install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage -d htmlcov
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - pip install coveralls
  - coveralls
